### ISSUE TITLE
Ability to sort by creation date/timestamp

### ISSUE THREAD

**Issue by geekpete** [laktak/todd#3]
I didn't realise the create date was being added by default as it was hidden.
So just the ability to sort by created date might be handy.

**Comment by laktak** [comment]
You can toggle it with 's'.

**Comment by geekpete** [comment]
`s` toggles between due date and priority.
When a new task is created the current date is prepended at the start of the line, this is the create date I want to be able to sort by.
This will let me see the oldest tasks in my list and allow me to purge/prioritise these as a cleanup sweep.

**Comment by laktak** [comment]
Maybe you missed the commit above my comment? Please try after updating.

**Comment by geekpete** [comment]
Ah so sorry, will test, thanks.
