### ISSUE TITLE
Sort and Filter by Project

### ISSUE THREAD

**Issue by meatballs** [laktak/todd#4]
Excellent TUI!! Many thanks indeed.

I can see that projects are scanned on a task, but I can't see a column for them or the ability to sort/filter.

**Comment by laktak** [comment]
Thanks ;)

I've renamed them to tags, not sure why they were called projects before. Since you can have any number of tags a separate column does not make sense IMO.

For now you can use the regular filter. Type `/` followed by `+` and the tag name like `+tag`. 

Does that help you?

**Comment by meatballs** [comment]
Yep - I've been using the regular filter but what I'd really like is something like the filter pane in todotxt-machine. There, similar to the context switching in todd, you could select which project(s) to include in the list. (Even the simple colourisation of the project/tag in the task list would be useful).

Also, you can have any number of contexts (Rule 3, https://github.com/todotxt/todo.txt) and this works fine already in todd.

**Comment by meatballs** [comment]
(I'm poking around the code to see if I can help with this, but I've never done any TUI work before, so it may take me a while to contribute).

**Comment by laktak** [comment]
> Also, you can have any number of contexts (Rule 3, https://github.com/todotxt/todo.txt) and this works fine already in todd.

You are right - I missed that.
