### ISSUE TITLE
Multiple Contexts

### ISSUE THREAD

**Issue by meatballs** [laktak/todd#5]
It would be very useful to be able to select multiple contexts in the swithching pane

Use case:

I have tasks that can only be done at home and others only in my office, but there are some that can be done at either as long as i have my laptop and an internet connection.

If I'm at the office, I might want to select both @office and @online as my current contexts.

Alternatively, if I could exclude the @home context, that would also be neat!

**Comment by laktak** [comment]
Hmm, I'm not sure about that. Would you manually select your contexts every time? Would you need views to define a set of contexts? Excluding would only work in your use case.

As an alternative you could just switch the context when you check your tasks.

**Comment by meatballs** [comment]
Actually, I've found that using multiple contexts works just fine. For those tasks that can be done at either home or office, I put both contexts on the task and they appear whichever of those two is selected.
